"""The 1024x600 skin.

Seeded by tools/gen_skin_seed.py from SKIN_1280 (scale 0.800 x 0.833);
values marked TODO are mechanical scalings pending hand-tuning on the panel.
"""

from .schema import (
    DashboardFonts,
    DashboardSkin,
    DeltaStyle,
    HeaderSkin,
    KeyboardSkin,
    NumpadSkin,
    OverlaySkin,
    RpmStyle,
    ScrollbarStyle,
    SetupSkin,
    Skin,
    SlotDots,
    TireGrid,
    ToggleStyle,
    WidgetStyle,
)

SKIN_1024 = Skin(
    name="1024x600",
    size=(1024, 600),
    dashboard=DashboardSkin(
        gear_rect=(512, 323, 149, 193),
        speed_rect=(512, 77, 176, 117),
        rpm_rect=(512, 155, 157, 62),
        delta_rect=(875, 257, 269, 125),
        fastest_lap_rect=(149, 57, 282, 78),
        predicted_lap_rect=(149, 136, 282, 78),
        fuel_per_lap_rect=(78, 215, 140, 78),
        fuel_laps_rect=(219, 215, 140, 78),
        track_rect=(149, 378, 282, 78),
        lap_time_rect=(875, 378, 269, 83),
        lap_counter_rect=(938, 525, 72, 65),
        tire_grid=TireGrid(
            origin=(811, 18),
            cell=(98, 77),
            col_step=101,
            row_step=80,  # TODO tune
        ),
        status_strip_w=80,
        shift_l_on=72,
        shift_r_on=66,
        status_light_rect=(0, 45, 80, 187),
        status_light_dot_spacing=75,
        status_light_dot_radius=10,
        footer_y=530,
        button_h=60,
        setup_button_w=88,
        setup_button_font=24,
        setup_button_font_family="PIXEL_TYPE",
        setup_button_icon=28,
        setup_button_pad_top=6,
        slot_name_left_inset=96,
        slot_dots=SlotDots(
            center=(512, 583),
            radius=4,
            pitch=21,
        ),
        fonts=DashboardFonts(
            gear=212,  # TODO tune
            gear_family="D_DIN_EXP_BOLD",
            speed=86,  # TODO tune
            speed_family="D_DIN_EXP_BOLD",
            rpm_label=14,
            rpm_label_family="D_DIN_EXP_BOLD",
            delta=60,
            delta_family="D_DIN_EXP",
            delta_state=36,
            delta_state_family="D_DIN_EXP",
            tire=36,
            tire_family="D_DIN_EXP_BOLD",
            track=32,
            track_family="D_DIN_EXP",
            slot_name=32,
            slot_name_family="D_DIN_EXP_BOLD",
            lap_counter=36,
            lap_counter_family="D_DIN_EXP_BOLD",
            lap_time=52,
            lap_time_family="D_DIN_EXP",
            fastest_lap=52,
            fastest_lap_family="D_DIN_EXP",
            predicted_lap=52,
            predicted_lap_family="D_DIN_EXP",
            fuel=38,
            fuel_family="D_DIN_EXP",
        ),
        swipe_min_dx=144,
        swipe_max_dy=117,
        gear_color="WHITE",
        speed_color="WHITE",
        fastest_lap_color="WHITE",
        predicted_lap_color="WHITE",
        lap_time_color="WHITE",
        lap_counter_color="WHITE",
        track_color="WHITE",
        slot_name_color="WHITE",
        fuel_per_lap_color="WHITE",
        fuel_laps_color="WHITE",
        delta_gain_color="GREEN",
        delta_loss_color="LIGHT_RED",
        tire_gradient_top="DARK_GREY",
        tire_gradient_bottom="RPM_RED",
        rpm_scale_color="LIGHT_GREY",
        rpm_redline_color="LIGHT_RED",
        status_light_tc_color="YELLOW",
        status_light_asm_color="BLUE",
        slot_dot_active_color="WHITE",
        slot_dot_inactive_color="DARKER_GREY",
    ),
    style=WidgetStyle(
        header_font_size=24,  # TODO tune
        header_font_family="PIXEL_TYPE",
        bg_color="BLACK",
        text_color="WHITE",
        border_color="WHITE",
        header_margin=6,
        value_offset_y=3,
        border_width=2,
        border_radius=3,
        digit_gap=-2,
        delta=DeltaStyle(
            seg_width=10,
            seg_height=16,
            seg_gap=2,
            seg_slant=6,
            seg_y_offset=6,
            value_offset_y=13,
            state_offset_y=8,
        ),
        rpm=RpmStyle(
            padding_x=5,
            padding_y=2,
            tick_major_len=6,
            tick_minor_len=2,
            tick_major_w=2,
            tick_minor_w=2,
            label_gap=5,
        ),
        scrollbar=ScrollbarStyle(
            track_width=6,
            thumb_color="BLUE",
            track_margin_right=13,
            min_thumb_height=27,
            track_hit_pad=16,
            drag_threshold=10,
        ),
        toggle=ToggleStyle(
            track_w=83,
            track_h=40,
            knob_margin=5,
            on_color="BLUE",
            off_color="DROPDOWN_LIGHT_GREY",
            knob_color="WHITE",
        ),
    ),
    header=HeaderSkin(
        title_topleft=(24, 8),
        title_font_size=40,  # TODO tune
        title_font_family="NOTOSANS_LIGHT",
        title_color="WHITE",
        line_y=83,
        line_color="BLUE",
        back_button_size=(59, 62),
        back_button_y=10,
        back_button_gap=10,
        back_button_icon=44,
    ),
    setup=SetupSkin(
        row_top=102,  # TODO tune
        row_pitch=103,  # TODO tune
        row_height=67,  # TODO tune
        row_font_size=26,
        row_font_family="NOTOSANS_REGULAR",
        icon_x=67,
        icon_size=28,
        label_x=99,
        label_dy=18,
        value_x=548,
        dropdown_x=526,
        separator_inset=32,
        separator_width=1,
        separator_clearance=2,
        chevron_icon_size=36,
        row_text_color="WHITE",
        separator_color="MID_GREY",
        visible_network_cells=4,  # TODO tune
    ),
    keyboard=KeyboardSkin(
        key_w=90,  # TODO tune
        key_h=65,  # TODO tune
        gap=8,  # TODO tune
        top=250,  # TODO tune
        row_step=75,  # TODO tune
        special_w=125,  # TODO tune
        space_w=480,  # TODO tune
        pw_row_y=157,
        pw_row_h=70,
        key_font=32,
        key_font_family="NOTOSANS_REGULAR",
        small_font=22,
        small_font_family="NOTOSANS_REGULAR",
        key_text_color="WHITE",
        ok_color="GREEN",
        pw_font=36,
        pw_font_family="NOTOSANS_REGULAR",
        rescan_size=(144, 58),
        rescan_font=32,
        rescan_font_family="PIXEL_TYPE",
        manual_label_font=32,
        manual_label_font_family="PIXEL_TYPE",
        manual_field_font=28,
        manual_field_font_family="NOTOSANS_REGULAR",
        manual_ssid_label_pos=(32, 98),
        manual_pw_label_pos=(32, 172),
        manual_field_rect=(288, 92, 448, 53),
        manual_pw_left=288,
    ),
    numpad=NumpadSkin(
        buttons_per_row=3,
        button_dims=(91, 65),
        button_margin=6,
        offset=(50, 190),
        recent_position=(658, 150),
        recent_per_row=1,
        recent_dims=(224, 62),
        recent_margin=10,
        recent_offset=(544, 175),
        key_font=28,
        key_font_family="NOTOSANS_REGULAR",
        field_rect=(50, 118, 285, 63),
        field_font=28,
        field_font_family="NOTOSANS_REGULAR",
        del_rect=(333, 118, 88, 63),
        ok_rect=(339, 332, 80, 137),
        recent_label_font=36,
        recent_label_font_family="PIXEL_TYPE",
        ok_color="GREEN",
        del_color="LIGHT_RED",
    ),
    overlays=OverlaySkin(
        wifi_pill_height=47,
        wifi_pill_center_y=470,
        wifi_pill_pad_x=22,
        wifi_pill_font=20,
        wifi_pill_font_family="D_DIN",
        feed_card_size=(688, 283),
        feed_card_radius=8,
        feed_title_font=36,
        feed_title_font_family="D_DIN_EXP_BOLD",
        feed_body_font=22,
        feed_body_font_family="NOTOSANS_REGULAR",
        feed_button_font=32,
        feed_button_font_family="PIXEL_TYPE",
        feed_title_top=38,
        feed_body_top=110,
        feed_body_line_pitch=35,
        feed_button_size=(208, 58),
        feed_button_bottom_margin=33,
        wifi_pill_border_color="MID_GREY",
        feed_accent_color="ORANGE",
    ),
)
