"""The 1280x720 skin — the original design, extracted verbatim.

This is the layout the HMI has always shipped: the Raspberry Pi Touch
Display 2 renders it 1:1 (the 270-degree rotation happens in the GPU
presentation path, no resampling), and it doubles as the dev-window layout.
Values are copied from their previous homes (``ui/constants.py``, the
plugin rect literals, ``ListItem`` class attrs, the overlay-window module
constants, ``Widget.__init__`` defaults) and must stay identical to them
until the last legacy consumer is migrated — the test suite pins the
equivalences.
"""

from .schema import (
    DashboardFonts,
    DashboardSkin,
    DeltaStyle,
    HeaderSkin,
    KeyboardSkin,
    NumpadSkin,
    OverlaySkin,
    RpmStyle,
    ScrollbarStyle,
    SetupSkin,
    Skin,
    SlotDots,
    TireGrid,
    ToggleStyle,
    WidgetStyle,
)

SKIN_1280 = Skin(
    name="1280x720",
    size=(1280, 720),
    dashboard=DashboardSkin(
        # Center dial column.
        gear_rect=(640, 388, 186, 232),
        speed_rect=(640, 92, 220, 140),
        rpm_rect=(640, 186, 196, 74),
        # Right column (pre-shift).
        delta_rect=(1094, 308, 336, 150),
        lap_time_rect=(1094, 454, 336, 100),
        lap_counter_rect=(1172, 630, 90, 78),  # topleft
        tire_grid=TireGrid(
            origin=(1014, 22),
            cell=(122, 92),
            col_step=126,
            row_step=96,
        ),
        # Left column (pre-shift).
        fastest_lap_rect=(186, 68, 352, 94),
        predicted_lap_rect=(186, 163, 352, 94),
        fuel_per_lap_rect=(97, 258, 175, 94),
        fuel_laps_rect=(274, 258, 175, 94),
        track_rect=(186, 454, 352, 94),
        # Bezel status-LED strips.
        status_strip_w=100,
        shift_l_on=90,  # strip_w - 10
        shift_r_on=82,  # strip_w - 18
        status_light_rect=(0, 54, 100, 224),
        status_light_dot_spacing=90,
        status_light_dot_radius=13,
        # Footer chrome.
        footer_y=636,  # 720 - button_h - 2*6
        button_h=72,
        setup_button_w=110,
        setup_button_font=32,
        setup_button_font_family="PIXEL_TYPE",
        setup_button_icon=34,
        setup_button_pad_top=8,
        slot_name_left_inset=120,
        slot_dots=SlotDots(center=(640, 700), radius=5, pitch=26),
        fonts=DashboardFonts(
            gear=264,
            gear_family="D_DIN_EXP_BOLD",
            speed=108,
            speed_family="D_DIN_EXP_BOLD",
            rpm_label=18,
            rpm_label_family="D_DIN_EXP_BOLD",
            delta=74,
            delta_family="D_DIN_EXP",
            delta_state=46,
            delta_state_family="D_DIN_EXP",
            tire=44,
            tire_family="D_DIN_EXP_BOLD",
            track=40,
            track_family="D_DIN_EXP",
            slot_name=40,
            slot_name_family="D_DIN_EXP_BOLD",
            lap_counter=44,
            lap_counter_family="D_DIN_EXP_BOLD",
            lap_time=64,
            lap_time_family="D_DIN_EXP",
            fastest_lap=64,
            fastest_lap_family="D_DIN_EXP",
            predicted_lap=64,
            predicted_lap_family="D_DIN_EXP",
            fuel=48,
            fuel_family="D_DIN_EXP",
        ),
        swipe_min_dx=180,
        swipe_max_dy=140,
        gear_color="WHITE",
        speed_color="WHITE",
        fastest_lap_color="WHITE",
        predicted_lap_color="WHITE",
        lap_time_color="WHITE",
        lap_counter_color="WHITE",
        track_color="WHITE",
        slot_name_color="WHITE",
        fuel_per_lap_color="WHITE",
        fuel_laps_color="WHITE",
        delta_gain_color="GREEN",
        delta_loss_color="LIGHT_RED",
        tire_gradient_top="DARK_GREY",
        tire_gradient_bottom="RPM_RED",
        rpm_scale_color="LIGHT_GREY",
        rpm_redline_color="LIGHT_RED",
        status_light_tc_color="YELLOW",
        status_light_asm_color="BLUE",
        slot_dot_active_color="WHITE",
        slot_dot_inactive_color="DARKER_GREY",
    ),
    style=WidgetStyle(
        header_font_size=32,
        header_font_family="PIXEL_TYPE",
        bg_color="BLACK",
        text_color="WHITE",
        border_color="LIGHT_GREY",
        header_margin=8,
        value_offset_y=4,
        border_width=2,
        border_radius=4,
        digit_gap=-2,
        delta=DeltaStyle(
            seg_width=12,
            seg_height=20,
            seg_gap=3,
            seg_slant=8,
            seg_y_offset=8,
            value_offset_y=16,
            state_offset_y=10,
        ),
        rpm=RpmStyle(
            padding_x=6,
            padding_y=2,
            tick_major_len=7,
            tick_minor_len=3,
            tick_major_w=3,
            tick_minor_w=2,
            label_gap=6,
        ),
        scrollbar=ScrollbarStyle(
            track_width=8,
            thumb_color="BLUE",
            track_margin_right=16,
            min_thumb_height=32,
            track_hit_pad=20,
            drag_threshold=12,
        ),
        toggle=ToggleStyle(track_w=104, track_h=48, knob_margin=6, on_color="BLUE", off_color="DROPDOWN_LIGHT_GREY", knob_color="WHITE"),
    ),
    header=HeaderSkin(
        title_topleft=(30, 10),
        title_font_size=50,
        title_font_family="NOTOSANS_LIGHT",
        title_color="WHITE",
        line_y=100,
        line_color="BLUE",
        back_button_size=(74, 74),
        back_button_y=12,
        back_button_gap=12,
        back_button_icon=54,
    ),
    setup=SetupSkin(
        # 5 uniform cells span the header line (y=100) to the screen
        # bottom (720): pitch = 620 / 5.
        row_top=122,
        row_pitch=124,
        row_height=80,
        row_font_size=32,
        row_font_family="NOTOSANS_REGULAR",
        icon_x=84,
        icon_size=34,
        label_x=124,
        label_dy=22,
        value_x=685,
        dropdown_x=658,
        separator_inset=40,
        separator_width=1,
        separator_clearance=2,
        chevron_icon_size=46,
        row_text_color="WHITE",
        separator_color="MID_GREY",
        visible_network_cells=4,
    ),
    keyboard=KeyboardSkin(
        key_w=112,
        key_h=78,
        gap=10,
        top=300,
        row_step=90,  # key_h + 12
        special_w=156,
        space_w=600,
        pw_row_y=188,
        pw_row_h=84,
        key_font=40,
        key_font_family="NOTOSANS_REGULAR",
        small_font=28,
        small_font_family="NOTOSANS_REGULAR",
        key_text_color="WHITE",
        ok_color="GREEN",
        pw_font=44,
        pw_font_family="NOTOSANS_REGULAR",
        rescan_size=(180, 70),
        rescan_font=40,
        rescan_font_family="PIXEL_TYPE",
        manual_label_font=40,
        manual_label_font_family="PIXEL_TYPE",
        manual_field_font=36,
        manual_field_font_family="NOTOSANS_REGULAR",
        manual_ssid_label_pos=(40, 118),
        manual_pw_label_pos=(40, 206),
        manual_field_rect=(360, 110, 560, 64),
        manual_pw_left=360,
    ),
    numpad=NumpadSkin(
        buttons_per_row=3,
        button_dims=(114, 78),
        button_margin=7,
        offset=(62, 228),
        recent_position=(822, 180),
        recent_per_row=1,
        recent_dims=(280, 74),
        recent_margin=12,
        recent_offset=(680, 210),
        key_font=34,
        key_font_family="NOTOSANS_REGULAR",
        field_rect=(62, 142, 356, 76),
        field_font=36,
        field_font_family="NOTOSANS_REGULAR",
        del_rect=(416, 142, 110, 76),
        ok_rect=(424, 398, 100, 164),
        recent_label_font=46,
        recent_label_font_family="PIXEL_TYPE",
        ok_color="GREEN",
        del_color="LIGHT_RED",
    ),
    overlays=OverlaySkin(
        # The shared status pill sits between the track/lap row and the
        # footer: gear ends at 504, footer ink starts at 630 (see
        # status_pill.py / no_signal_window.py for the why).
        wifi_pill_height=56,
        wifi_pill_center_y=564,
        wifi_pill_pad_x=28,
        wifi_pill_font=26,
        wifi_pill_font_family="D_DIN",
        feed_card_size=(860, 340),
        feed_card_radius=10,
        feed_title_font=44,
        feed_title_font_family="D_DIN_EXP_BOLD",
        feed_body_font=28,
        feed_body_font_family="NOTOSANS_REGULAR",
        feed_button_font=40,
        feed_button_font_family="PIXEL_TYPE",
        feed_title_top=46,
        feed_body_top=132,
        feed_body_line_pitch=42,
        feed_button_size=(260, 70),
        feed_button_bottom_margin=40,
        wifi_pill_border_color="MID_GREY",
        feed_accent_color="ORANGE",
    ),
)
