"""The 800x480 skin.

Seeded by tools/gen_skin_seed.py from SKIN_1280 (scale 0.625 x 0.667);
values marked TODO are mechanical scalings pending hand-tuning on the panel.
"""

from .schema import (
    DashboardFonts,
    DashboardSkin,
    DeltaStyle,
    HeaderSkin,
    KeyboardSkin,
    NumpadSkin,
    OverlaySkin,
    RpmStyle,
    ScrollbarStyle,
    SetupSkin,
    Skin,
    SlotDots,
    TireGrid,
    ToggleStyle,
    WidgetStyle,
)

SKIN_800 = Skin(
    name="800x480",
    size=(800, 480),
    dashboard=DashboardSkin(
        gear_rect=(400, 259, 116, 155),
        speed_rect=(400, 61, 138, 93),
        rpm_rect=(400, 124, 132, 56),
        delta_rect=(684, 205, 210, 100),
        fastest_lap_rect=(116, 45, 220, 63),
        predicted_lap_rect=(116, 109, 220, 63),
        fuel_per_lap_rect=(61, 173, 109, 63),
        fuel_laps_rect=(171, 173, 109, 63),
        track_rect=(116, 303, 220, 63),
        lap_time_rect=(684, 303, 210, 67),
        lap_counter_rect=(732, 420, 56, 52),
        tire_grid=TireGrid(
            origin=(634, 15),
            cell=(76, 61),
            col_step=79,
            row_step=64,
        ),
        status_strip_w=62,
        shift_l_on=56,
        shift_r_on=51,
        status_light_rect=(0, 36, 62, 149),
        status_light_dot_spacing=60,
        status_light_dot_radius=8,
        footer_y=424,
        button_h=48,
        setup_button_w=69,
        setup_button_font=24,
        setup_button_font_family="PIXEL_TYPE",
        setup_button_icon=22,
        setup_button_pad_top=5,
        slot_name_left_inset=75,
        slot_dots=SlotDots(
            center=(400, 467),
            radius=3,
            pitch=16,
        ),
        fonts=DashboardFonts(
            gear=164,
            gear_family="D_DIN_EXP_BOLD",
            speed=68,
            speed_family="D_DIN_EXP_BOLD",
            rpm_label=12,
            rpm_label_family="D_DIN_EXP_BOLD",
            delta=46,
            delta_family="D_DIN_EXP",
            delta_state=28,
            delta_state_family="D_DIN_EXP",
            tire=28,
            tire_family="D_DIN_EXP_BOLD",
            track=24,
            track_family="D_DIN_EXP",
            slot_name=24,
            slot_name_family="D_DIN_EXP_BOLD",
            lap_counter=28,
            lap_counter_family="D_DIN_EXP_BOLD",
            lap_time=40,
            lap_time_family="D_DIN_EXP",
            fastest_lap=40,
            fastest_lap_family="D_DIN_EXP",
            predicted_lap=40,
            predicted_lap_family="D_DIN_EXP",
            fuel=30,
            fuel_family="D_DIN_EXP",
        ),
        swipe_min_dx=112,
        swipe_max_dy=93,
        gear_color="WHITE",
        speed_color="WHITE",
        fastest_lap_color="WHITE",
        predicted_lap_color="WHITE",
        lap_time_color="WHITE",
        lap_counter_color="WHITE",
        track_color="WHITE",
        slot_name_color="WHITE",
        fuel_per_lap_color="WHITE",
        fuel_laps_color="WHITE",
        delta_gain_color="GREEN",
        delta_loss_color="LIGHT_RED",
        tire_gradient_top="DARK_GREY",
        tire_gradient_bottom="RPM_RED",
        rpm_scale_color="LIGHT_GREY",
        rpm_redline_color="LIGHT_RED",
        status_light_tc_color="YELLOW",
        status_light_asm_color="BLUE",
        slot_dot_active_color="WHITE",
        slot_dot_inactive_color="DARKER_GREY",
    ),
    style=WidgetStyle(
        header_font_size=24,
        header_font_family="PIXEL_TYPE",
        bg_color="BLACK",
        text_color="WHITE",
        border_color="WHITE",
        header_margin=5,
        value_offset_y=2,
        border_width=1,
        border_radius=2,
        digit_gap=-1,
        delta=DeltaStyle(
            seg_width=8,
            seg_height=12,
            seg_gap=2,
            seg_slant=5,
            seg_y_offset=5,
            value_offset_y=10,
            state_offset_y=6,
        ),
        rpm=RpmStyle(
            padding_x=4,
            padding_y=1,
            tick_major_len=4,
            tick_minor_len=2,
            tick_major_w=2,
            tick_minor_w=1,
            label_gap=4,
        ),
        scrollbar=ScrollbarStyle(
            track_width=5,
            thumb_color="BLUE",
            track_margin_right=10,
            min_thumb_height=21,
            track_hit_pad=12,
            drag_threshold=8,
        ),
        toggle=ToggleStyle(
            track_w=65,
            track_h=32,
            knob_margin=4,
            on_color="BLUE",
            off_color="DROPDOWN_LIGHT_GREY",
            knob_color="WHITE",
        ),
    ),
    header=HeaderSkin(
        title_topleft=(19, 7),
        title_font_size=32,
        title_font_family="NOTOSANS_LIGHT",
        title_color="WHITE",
        line_y=67,
        line_color="BLUE",
        back_button_size=(46, 49),
        back_button_y=8,
        back_button_gap=8,
        back_button_icon=34,
    ),
    setup=SetupSkin(
        # 5 uniform cells span the header line (67) to the bottom (480),
        # as on the other two skins — 5 rows fit before the list scrolls.
        row_top=81,
        row_pitch=82,
        row_height=54,
        row_font_size=22,
        row_font_family="NOTOSANS_REGULAR",
        icon_x=52,
        icon_size=24,
        label_x=78,
        label_dy=12,
        value_x=428,
        dropdown_x=411,
        separator_inset=25,
        separator_width=1,
        separator_clearance=2,
        chevron_icon_size=30,
        row_text_color="WHITE",
        separator_color="MID_GREY",
        visible_network_cells=4,
    ),
    keyboard=KeyboardSkin(
        key_w=72,
        key_h=52,
        gap=6,
        top=200,
        row_step=60,
        special_w=98,
        space_w=375,
        pw_row_y=125,
        pw_row_h=56,
        key_font=24,
        key_font_family="NOTOSANS_REGULAR",
        small_font=18,
        small_font_family="NOTOSANS_REGULAR",
        key_text_color="WHITE",
        ok_color="GREEN",
        pw_font=28,
        pw_font_family="NOTOSANS_REGULAR",
        rescan_size=(112, 47),
        rescan_font=24,
        rescan_font_family="PIXEL_TYPE",
        manual_label_font=24,
        manual_label_font_family="PIXEL_TYPE",
        manual_field_font=22,
        manual_field_font_family="NOTOSANS_REGULAR",
        manual_ssid_label_pos=(25, 79),
        manual_pw_label_pos=(25, 137),
        manual_field_rect=(225, 73, 350, 43),
        manual_pw_left=225,
    ),
    numpad=NumpadSkin(
        buttons_per_row=3,
        button_dims=(71, 52),
        button_margin=4,
        offset=(39, 152),
        recent_position=(514, 120),
        recent_per_row=1,
        recent_dims=(175, 49),
        recent_margin=8,
        recent_offset=(425, 140),
        key_font=22,
        key_font_family="NOTOSANS_REGULAR",
        field_rect=(39, 95, 222, 51),
        field_font=22,
        field_font_family="NOTOSANS_REGULAR",
        del_rect=(260, 95, 69, 51),
        ok_rect=(265, 265, 62, 109),
        recent_label_font=28,
        recent_label_font_family="PIXEL_TYPE",
        ok_color="GREEN",
        del_color="LIGHT_RED",
    ),
    overlays=OverlaySkin(
        wifi_pill_height=37,
        wifi_pill_center_y=376,
        wifi_pill_pad_x=18,
        wifi_pill_font=16,
        wifi_pill_font_family="D_DIN",
        feed_card_size=(538, 227),
        feed_card_radius=6,
        feed_title_font=28,
        feed_title_font_family="D_DIN_EXP_BOLD",
        feed_body_font=18,
        feed_body_font_family="NOTOSANS_REGULAR",
        feed_button_font=24,
        feed_button_font_family="PIXEL_TYPE",
        feed_title_top=31,
        feed_body_top=88,
        feed_body_line_pitch=28,
        feed_button_size=(162, 47),
        feed_button_bottom_margin=27,
        wifi_pill_border_color="MID_GREY",
        feed_accent_color="ORANGE",
    ),
)
