from ..peripherals.display import LOGICAL_HEIGHT, LOGICAL_WIDTH

# ------------------------
#  VALUES
# ------------------------
LAP_DEFAULT_VALUE = 0.0

# ------------------------
# UI
# ------------------------
# The UI is laid out against the fixed logical design resolution (1280x720);
# Display scales/rotates it onto the physical panel. See display.py.
SCREEN_WIDTH = LOGICAL_WIDTH
SCREEN_HEIGHT = LOGICAL_HEIGHT

BUTTON_HEIGHT = 72

FOOTER_BUTTONGROUP_MARGIN = 6
FOOTER_BUTTONGROUP_X = 10
FOOTER_BUTTONGROUP_Y = (
    SCREEN_HEIGHT
    - BUTTON_HEIGHT
    - (FOOTER_BUTTONGROUP_MARGIN + FOOTER_BUTTONGROUP_MARGIN)
)

LAP_WIDGET_Y = FOOTER_BUTTONGROUP_Y - FOOTER_BUTTONGROUP_MARGIN
LAP_WIDGET_HEIGHT = BUTTON_HEIGHT + FOOTER_BUTTONGROUP_MARGIN

# header
HEADER_TITLE_TOPLEFT = (30, 30)
HEADER_TITLE_FONT_SIZE = 74
HEADER_LINE_TOPLEFT = (0, 100)
HEADER_BACKBUTTON_Y = 12
HEADER_BACKBUTTON_GAP = 12
HEADER_BACKBUTTON_SIZE = (74, 74)
HEADER_BACKBUTTON_POSITION = (
    SCREEN_WIDTH - HEADER_BACKBUTTON_SIZE[0] - HEADER_BACKBUTTON_GAP,
    HEADER_BACKBUTTON_Y,
)

# enter_ip_state
BUTTONS_PER_ROW = 3
BUTTON_DIMENSIONS = (114, 78)
BUTTON_MARGIN = 7
BUTTON_GRID_OFFSET = (
    BUTTON_DIMENSIONS[0] + BUTTON_MARGIN,
    BUTTON_DIMENSIONS[1] + BUTTON_MARGIN,
)
NUMPAD_OFFSET = (62, 228)
RECENT_CONNECTIONS_POSITION = (822, 180)
RECENT_BUTTONS_PER_ROW = 1
RECENT_BUTTONS_DIMENSIONS = (280, 74)
RECENT_BUTTONS_MARGIN = 12
RECENT_BUTTONS_GRID_OFFSET = (
    RECENT_BUTTONS_DIMENSIONS[0] + RECENT_BUTTONS_MARGIN,
    RECENT_BUTTONS_DIMENSIONS[1] + RECENT_BUTTONS_MARGIN,
)
RECENT_BUTTONS_OFFSET = (680, 210)

# wifi_setup_state
# Network list (scan phase) — vertical stack of full-width rows.
WIFI_LIST_X = 30
WIFI_LIST_TOP = 120
WIFI_ROW_HEIGHT = 78
WIFI_ROW_GAP = 8
WIFI_ROW_WIDTH = SCREEN_WIDTH - 2 * WIFI_LIST_X
WIFI_MAX_ROWS = 6  # scanned networks shown before the "Other" row

# On-screen QWERTY keyboard (password phase).
WIFI_KEY_W = 112
WIFI_KEY_H = 78
WIFI_KEY_GAP = 10
WIFI_KEYBOARD_TOP = 300
WIFI_KEY_ROW_STEP = WIFI_KEY_H + 12
WIFI_SPECIAL_W = 156  # shift / backspace / mode / OK
WIFI_SPACE_W = 600
