from __future__ import annotations

from enum import Enum
from importlib.resources import as_file, files

import pygame

from ..peripherals.display import scale_factors, scale_uniform

_font_cache: dict[tuple[FontFamily, int], pygame.font.Font] = {}


# ---------------------------------------------------------------------------
# Spec-space scaling (custom dashboards + self-contained decoration)
#
# The standard HMI takes its geometry from the per-resolution skins
# (ui/skins/) in native pixels — skinned code never calls these helpers.
# They map the fixed 1280x720 spec space to the active panel's logical
# size, and remain for exactly two uses:
#
# * custom-dashboard layouts, which are authored in spec space on every
#   panel (see ui/widgets/registry.py);
# * self-contained decoration inside a widget (small paddings, icon
#   nudges, radio glyphs) that isn't worth a skin field — safe as long as
#   the scaled value is never mixed arithmetically with a skin value that
#   was scaled differently.
#
# Call them at construction time (after the display profile has been set).
# ---------------------------------------------------------------------------
def sx(value: float) -> int:
    """Scale an x-axis (horizontal) design value."""
    return round(value * scale_factors()[0])


def sy(value: float) -> int:
    """Scale a y-axis (vertical) design value."""
    return round(value * scale_factors()[1])


def su(value: float) -> int:
    """Scale a size/radius/gap uniformly (fonts, icons, square dimensions)."""
    return round(value * scale_uniform())


def srect(x: float, y: float, w: float, h: float) -> tuple[int, int, int, int]:
    """Scale a design-space rect (x, y, w, h)."""
    return (sx(x), sy(y), sx(w), sy(h))


def spos(x: float, y: float) -> tuple[int, int]:
    """Scale a design-space position (x, y)."""
    return (sx(x), sy(y))


# Gamma applied to the ramp position. Slightly above 1 holds the top colour
# a little longer and brightens the lower half — the look the gauge panels
# (tyre temps) use. Try 1.5 / 2.0 / 2.5 for a stronger effect.
GRADIENT_EXPONENT = 1.1


def vertical_gradient(
    size: tuple[int, int],
    top_color: tuple[int, int, int],
    bottom_color: tuple[int, int, int],
    exponent: float = GRADIENT_EXPONENT,
) -> pygame.Surface:
    """A top-to-bottom colour ramp filling `size`.

    Shared so every gradient surface in the UI — gauge panel backgrounds and
    the NO SIGNAL banner — is generated by one piece of code and matches.
    """
    width, height = size
    surf = pygame.Surface(size)

    if height <= 1:
        surf.fill(top_color)
        return surf

    for y in range(height):
        t = (y / (height - 1)) ** exponent
        surf.fill(
            tuple(round(a + (b - a) * t) for a, b in zip(top_color, bottom_color)),
            (0, y, width, 1),
        )
    return surf


def load_font_px(size: int, family: FontFamily) -> pygame.font.Font:
    """Load a font at an exact pixel size (no scaling applied).

    Skinned code calls this with native sizes from ``active_skin()``;
    legacy design-space callers go through :func:`load_font`, which scales
    first. Both share one cache keyed by the final pixel size.
    """
    size = max(1, int(size))
    key = (family, size)
    if key in _font_cache:
        return _font_cache[key]

    font_res = files("instrument_cluster").joinpath(family.relpath)
    with as_file(font_res) as font_path:
        font = pygame.font.Font(str(font_path), size)

    _font_cache[key] = font
    return font


def load_font(size: int, family: FontFamily) -> pygame.font.Font:
    # Fonts are authored in design pixels; scale to the active panel so text is
    # rendered at native resolution (crisp) rather than scaled after the fact.
    # Pixeltype renders ragged off its 8px grid, so scaled sizes snap to it —
    # a no-op at scale 1.0, where authored sizes are already on-grid.
    scaled = max(1, su(size))
    if family is FontFamily.PIXEL_TYPE and scale_uniform() != 1.0:
        scaled = max(8, round(scaled / 8) * 8)
    return load_font_px(scaled, family)


def load_image(relpath: str) -> pygame.Surface:
    """Load a bundled image asset (path relative to the package root)."""
    res = files("instrument_cluster").joinpath(relpath)
    with as_file(res) as path:
        return pygame.image.load(str(path))


class FontFamily(Enum):
    PIXEL_TYPE = ("pixeltype", "pixeltype")
    MATERIAL_SYMBOLS = ("material_symbols", "material-symbols-rounded-latin-300-normal")
    D_DIN_EXP_BOLD = ("d-din", "D-DINExp-Bold")
    D_DIN_EXP = ("d-din", "D-DINExp")
    D_DIN = ("d-din", "D-DIN")
    NOTOSANS_REGULAR = ("noto_sans", "NotoSans-Regular")
    NOTOSANS_LIGHT = ("noto_sans", "NotoSans-Light")
    NOTOSANS_EXTRA_LIGHT = ("noto_sans", "NotoSans-ExtraLight")

    def __init__(self, subdir: str, basename: str):
        self.subdir = subdir  # folder under assets/fonts
        self.basename = basename  # filename without .ttf

    @property
    def relpath(self) -> str:
        return f"assets/fonts/{self.subdir}/{self.basename}.ttf"
