from __future__ import annotations

from enum import Enum
from importlib.resources import as_file, files

import pygame

from ..peripherals.display import scale_factors, scale_uniform

_font_cache: dict[tuple[FontFamily, int], pygame.font.Font] = {}


# ---------------------------------------------------------------------------
# Spec-space scaling (custom dashboards + self-contained decoration)
#
# The standard HMI takes its geometry from the per-resolution skins
# (ui/skins/) in native pixels — skinned code never calls these helpers.
# They map the fixed 1280x720 spec space to the active panel's logical
# size, and remain for exactly two uses:
#
# * custom-dashboard layouts, which are authored in spec space on every
#   panel (see ui/widgets/registry.py);
# * self-contained decoration inside a widget (small paddings, icon
#   nudges, radio glyphs) that isn't worth a skin field — safe as long as
#   the scaled value is never mixed arithmetically with a skin value that
#   was scaled differently.
#
# Call them at construction time (after the display profile has been set).
# ---------------------------------------------------------------------------
def sx(value: float) -> int:
    """Scale an x-axis (horizontal) design value."""
    return round(value * scale_factors()[0])


def sy(value: float) -> int:
    """Scale a y-axis (vertical) design value."""
    return round(value * scale_factors()[1])


def su(value: float) -> int:
    """Scale a size/radius/gap uniformly (fonts, icons, square dimensions)."""
    return round(value * scale_uniform())


def srect(x: float, y: float, w: float, h: float) -> tuple[int, int, int, int]:
    """Scale a design-space rect (x, y, w, h)."""
    return (sx(x), sy(y), sx(w), sy(h))


def spos(x: float, y: float) -> tuple[int, int]:
    """Scale a design-space position (x, y)."""
    return (sx(x), sy(y))


# Gamma applied to the ramp position. Slightly above 1 holds the top colour
# a little longer and brightens the lower half — the look the gauge panels
# (tyre temps) use. Try 1.5 / 2.0 / 2.5 for a stronger effect.
GRADIENT_EXPONENT = 1.1


def opaque_layer(
    size: tuple[int, int], color: tuple[int, int, int]
) -> pygame.Surface:
    """A scratch layer filled opaque with ``color``. Draw on it, then seal it
    with :func:`seal_layer` before returning it to be blitted.

    For layers composed once and then re-blitted whole onto a widget's image
    (the RPM scales), where the destination pixels are *replaced*.

    ``pygame.Surface(size).convert()`` looks like the way to say "opaque",
    and it is what this used to be, but it is a trap: convert() copies the
    *display* format, and a plain (non-SCALED) macOS window is ARGB8888 — so
    the layer inherits an alpha channel that nothing initialises. Fills and
    ``draw.*`` write alpha 255 into it, but blitting antialiased text does
    not: the glyph pixels land with alpha 0, the copy carries that hole into
    the widget image, and the text is invisible wherever the widget's own
    image isn't fully opaque (any skin with a border radius). It cost the
    RPM scale its 0/2/4/6/8 labels on the desktop build; the Pi and the
    SCALED dev window never showed it, their formats having no alpha channel
    at all. So the channel is created explicitly and filled opaque here.
    """
    surf = pygame.Surface(size, pygame.SRCALPHA).convert_alpha()
    surf.fill((color[0], color[1], color[2], 255))
    return surf


def seal_layer(surf: pygame.Surface) -> pygame.Surface:
    """Finish an :func:`opaque_layer` so it blits as a raw copy.

    ``set_alpha(None)`` is the same raw-copy semantics
    ``Widget._refresh_base_image`` relies on: it replaces the destination
    pixels instead of compositing a layer that has nothing to composite —
    measured at 206 vs 2143 us for 900x120 on a Pi 4 at 1000 MHz, which was
    the single largest cost in the RPM widget.

    It must be the *last* thing done to the layer. A surface with blending
    switched off is also blended-into differently: antialiased text drawn
    onto it after this call lands with alpha 0 (verified on pygame 2.6.1 /
    SDL 2.28.4), which is the very hole :func:`opaque_layer` exists to avoid.
    """
    surf.set_alpha(None)
    return surf


def vertical_gradient(
    size: tuple[int, int],
    top_color: tuple[int, int, int],
    bottom_color: tuple[int, int, int],
    exponent: float = GRADIENT_EXPONENT,
) -> pygame.Surface:
    """A top-to-bottom colour ramp filling `size`.

    Shared so every gradient surface in the UI (the gauge panel
    backgrounds) is generated by one piece of code and matches.
    """
    width, height = size
    surf = pygame.Surface(size)

    if height <= 1:
        surf.fill(top_color)
        return surf

    for y in range(height):
        t = (y / (height - 1)) ** exponent
        surf.fill(
            tuple(round(a + (b - a) * t) for a, b in zip(top_color, bottom_color)),
            (0, y, width, 1),
        )
    return surf


# Sine-arch glow parameters, all fractions of the cell so one set of
# numbers holds the look at every size. GLOW_HEADROOM is the slice of panel
# height the arch's peak leaves free at the top; GLOW_BAND is the width of
# the transition, as a fraction of panel height — the arch line sits in its
# middle, so half the band bleeds either side of the curve. GLOW_CREST is
# an exponent on the sine: 1.0 is the plain curve, and below that the crest
# widens (the peak flattens out and the flanks steepen) without moving the
# peak or the corners.
GLOW_HEADROOM = 0.55  # 0.5
GLOW_BAND = 1.3  # 1.1
GLOW_CREST = 0.25


def arc_gradient(
    size: tuple[int, int],
    edge_color: tuple[int, int, int],
    glow_color: tuple[int, int, int],
    headroom: float = GLOW_HEADROOM,
    band: float = GLOW_BAND,
    crest: float = GLOW_CREST,
) -> pygame.Surface:
    """A glow bounded by a sine arch, fading to `edge_color` above it.

    The companion to :func:`vertical_gradient` for panels whose dark tone is
    a vignette rather than a strict top-to-bottom ramp. Fit half a sine
    period across the panel — bottom-left corner up over the middle and back
    down to the bottom-right corner, peaking `headroom` short of the top
    edge and broadened at the crest by `crest`. Below that curve is
    `glow_color`, above it `edge_color`, and the curve itself is the middle
    of the transition.

    Because the arch dives into the bottom corners, the dark closes in from
    both sides as well as from the top and meets in the top corners — the
    soft inner shadow that frames the value digits.
    """
    import numpy as np

    width, height = size
    if width <= 0 or height <= 0:
        return pygame.Surface((max(width, 1), max(height, 1)))

    span = max(1, width - 1)
    bottom = height - 1
    amplitude = (1.0 - headroom) * bottom
    arch = bottom - amplitude * np.sin(np.pi * np.arange(width) / span) ** crest

    # Signed distance to the arch, in half-bands: -1 at the top of the
    # transition, 0 on the curve, +1 at its bottom.
    half_band = max(1.0, band * bottom / 2.0)
    t = np.clip(
        0.5 + (np.arange(height)[:, None] - arch[None, :]) / (2.0 * half_band),
        0.0,
        1.0,
    )
    t = t * t * (3.0 - 2.0 * t)  # smoothstep: no seam where the band ends

    edge = np.array(edge_color, dtype=float)
    glow = np.array(glow_color, dtype=float)
    rgb = edge + (glow - edge) * t[:, :, None]

    surf = pygame.Surface(size)
    # surfarray is (x, y, rgb); the field above is built row-major.
    pygame.surfarray.blit_array(surf, rgb.transpose(1, 0, 2).round().astype("uint8"))
    return surf


def load_font_px(size: int, family: FontFamily) -> pygame.font.Font:
    """Load a font at an exact pixel size (no scaling applied).

    Skinned code calls this with native sizes from ``active_skin()``;
    legacy design-space callers go through :func:`load_font`, which scales
    first. Both share one cache keyed by the final pixel size.
    """
    size = max(1, int(size))
    key = (family, size)
    if key in _font_cache:
        return _font_cache[key]

    font_res = files("instrument_cluster").joinpath(family.relpath)
    with as_file(font_res) as font_path:
        font = pygame.font.Font(str(font_path), size)

    _font_cache[key] = font
    return font


def load_font(size: int, family: FontFamily) -> pygame.font.Font:
    # Fonts are authored in design pixels; scale to the active panel so text is
    # rendered at native resolution (crisp) rather than scaled after the fact.
    # Pixeltype renders ragged off its 8px grid, so scaled sizes snap to it —
    # a no-op at scale 1.0, where authored sizes are already on-grid.
    scaled = max(1, su(size))
    if family is FontFamily.PIXEL_TYPE and scale_uniform() != 1.0:
        scaled = max(8, round(scaled / 8) * 8)
    return load_font_px(scaled, family)


def load_image(relpath: str) -> pygame.Surface:
    """Load a bundled image asset (path relative to the package root)."""
    res = files("instrument_cluster").joinpath(relpath)
    with as_file(res) as path:
        return pygame.image.load(str(path))


class FontFamily(Enum):
    PIXEL_TYPE = ("pixeltype", "pixeltype")
    MATERIAL_SYMBOLS = ("material_symbols", "material-symbols-rounded-latin-300-normal")
    D_DIN_EXP_BOLD = ("d-din", "D-DINExp-Bold")
    D_DIN_EXP = ("d-din", "D-DINExp")
    D_DIN = ("d-din", "D-DIN")
    NOTOSANS_REGULAR = ("noto_sans", "NotoSans-Regular")
    NOTOSANS_LIGHT = ("noto_sans", "NotoSans-Light")
    NOTOSANS_EXTRA_LIGHT = ("noto_sans", "NotoSans-ExtraLight")

    def __init__(self, subdir: str, basename: str):
        self.subdir = subdir  # folder under assets/fonts
        self.basename = basename  # filename without .ttf

    @property
    def relpath(self) -> str:
        return f"assets/fonts/{self.subdir}/{self.basename}.ttf"
